<?php
defined('WEKIT_VERSION') or exit(403);
/**
 * 前台入口
 *
 * generated by phpwind.com
 */
class ApiController extends PwBaseController {
	
	public $action;
	
	public $url;
	
	public function beforeAction($handlerAdapter) {
		parent::beforeAction($handlerAdapter);
		//TODO do something before all the action
		$this->action = $this->getInput('action', 'post');
		$this->url = $this->getInput('url', 'post');
		if(!$this->action) {
			$code = $this->getInput('code', 'get');
			if($code) {
				$this->getJson($code);
			}
			$this->showError("禁止直接访问或者无action请求~~");
		}
	}
	
	public function run() {
		switch($this->action) {
			case 'checkurl':
				$this->check();
				break;
			case 'gethtml':
				$this->getHtml();
				break;
			case 'v':
				$this->v();
				break;
		}
		exit;
	}
	
	private function check() {
		$data = '<span class="tips_icon_error">';
		if(!WindValidator::isRequired($this->url)) {
			$data .= '域名不能为空！';
		} else if(!$this->isUrl($this->url)) {
			$data .= '"' . $this->url . '"格式不正确';
		} else {
			$d = $this->MedzDb();
			$d->setUrl($this->url);
			$d = $d->getByUrl();
			if(!empty($d) || $d['url'] == $this->url) {
				$data .= '该域名存在数据库，已被注册！';
			} else {
				echo 1;
				exit;
			}
		}
		echo $data .= '</span>';
	}
	
	private function getHtml() {
		$data = '';
		if($this->getInput("type", "post") == 1) {
			$data .= '<p>1.请下载校验文件 <a href="';
			$data .= WindUrlHelper::createUrl('app/MedzRegisterWebsite/api/run?code=' . md5($this->url));
			$data .= '" target="_blank">medz-reg-v.json</a>，并上传到网站根目录.(请勿修改其中内容，否则将验证失败)</p>';
			$data .= '<p>2.确保 <a href="';
			$data .= 'http://' . $this->url . '/medz-reg-v.json';
			$data .= '" target="_blank">';
			$data .= 'http://' . $this->url . '/medz-reg-v.json';
			$data .= '</a> 可以访问。</p>';
		} else {
			$data .= '<p>1.复制下面 meta 代码，并写入到网站首页的 head 标签内：</p>';
			$data .= '<p><code>&lt;meta name="medz_reg" content="' . md5(md5($this->url)) . '"/&gt;</code></p>';
			$data .= '<p>确保打开您的网站首页“<a href="';
			$data .= 'http://' . $this->url . '/';
			$data .= '" target="_blank">';
			$data .= 'http://' . $this->url . '/';
			$data .= '</a>” head 中包含上面的代码</p>';
		}
		echo $data;
	}
	
	private function getJson($code) {
		header("Content-type:application/text");
		header("Content-Disposition:attachment;filename='medz-reg-v.json'");
		echo md5($code);
		exit;
	}
	
	private function v() {
		$type = $this->getInput("type", "post");
		$websiteServer = $this->MedzWebsite($this->url);
		$d = $this->MedzDb();
		$d->setUrl($this->url);
		$d = $d->getByUrl();
		if(!empty($d) || $d['url'] == $this->url) {
			echo 2;
			exit;
		}
		if($type == 'file') {
			$websiteServer->setType('file');
			if($websiteServer->exec()) {
				echo 1;
				exit;
			}
		} else if($type == "meta") {
			$websiteServer->setType('meta');
			if($websiteServer->exec()) {
				echo 1;
				exit;
			}
		}
		echo 2;
		exit;
	}
	
	/**
	 * 验证是否是合法的url
	 * 
	 * @param string $string 待验证的字串
	 * @return boolean 如果是合法的url则返回true，否则返回false
	 */
	private static function isUrl($string) {
		return 0 < preg_match('/^(?:(?:[\w-]+\.)+[\w-]+(?:[\w-]*)?)$/', $string);
	}
	
	private function MedzDb() {
		return Wekit::load('EXT:MedzRegisterWebsite.service.helps.App_Medz_Db');
	}
	
	private function MedzWebsite($website = '') {
		Wind::import('EXT:MedzRegisterWebsite.service.helps.App_Medz_Website');
		return new App_Medz_Website($website);
	}
}
